name: ZAP POST DAST

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ZAP Automation
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          plan: post-dast.yaml

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zap-output
          path: post-dast-report.html
