name: ZAP Simple POST Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make workspace writable
        run: sudo chmod -R 777 .

      - name: Run ZAP with simple POST
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            /zap/zap.sh -cmd -autorun /zap/wrk/simple-post.yaml

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-output
          path: "*.html"
