name: ZAP API Scan (Debug)

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP API Scan with hooks (POST debug)
        run: |
          docker run \
            --tty \
            --rm \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-api-scan.py \
              -t /zap/wrk/simple-testfire-post.yaml \
              -f openapi \
              -d \
              -I \
              --hook=/zap/wrk/.zap/hooks.py \
              -r zap-report.html \
              -J zap-report.json

      - name: Upload ZAP HTML report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
